#%RAML 1.0 NamedExample
value: 
  employee: 
    email: james.gosling@revature.com
    firstName: James
    lastName: Gosling
  batches: 
    - 
      id: 121501
      batchId: Ix2x2UAB
      name: 1804  Apr16 -2
      startDate: 2018-04-23
      endDate: 2018-06-29
      skill: JTA
      location: Revature LLC, Reston VA 20190
      type: Revature
      qcNotes:
        - 
          noteId: 398328
          content: mock content
          week: 1
          batchId: Ix2x2UAB
          associateId: 654321
          employeeId: 123456
          type: QC_BATCH
          technicalStatus: Good
          createdOn: 01-01-2019
          lastUpdate: 01-01-2020
          categories:
            - 
              Java
      assessments:
        - 
          assessmentId: 177003
          rawScore: 100
          assessmentTitle: mock title
          assessmentType: Exam
          weekNumber: 1
          batchId: Ix2x2UAB
          assessmentCategory: 1
          skillCategory: Java
          assignmentDate: 01-01-2020
          average: 76.10