training-sapi:
  host: "self-training-service-sapi.us-e2.cloudhub.io"
  basepath: "/api"
  protocol: "HTTP"
  port: "80"
  
get-trainer-info:
  path: "/training"
  
get-batch-info:
  path: "/batch"
  
get-qc-notes:
  path: "/notes"
  
get-category:
  path: "/category"